### PR TITLE
IdentityAndConsentManagement meeting notes 2024-01-17

### PR DESCRIPTION
**Pull request by jpengar**
#### What type of PR is this?
* documentation

#### What this PR does / why we need it:

MoM of the call held in 2024-01-17

#### Which issue(s) this PR fixes:

None.

CC @MarkCornall @Elisabeth-Ericsson @FrimanJan @DT-DawidWroblewski

### CODE REVIEW

**Review by diegogonmar — APPROVED** [review]
LGTM

**Comment by shilpa-padgaonkar** [comment]
I would like to request here change from  "Shilpa indicates that she thinks the parts are actually saying the same thing, but from different starting points: define own CAMARA profile, not include default options from other profiles, use existing profile as inspiration. She suggests to start with a PR and discuss on that PR. Mark comments on the same line."

to

Shilpa indicates that she thinks that both Telefonica and DT are saying the same things but from different starting points: what she can suggest is to define own Camara profile, reuse what work has been done in the past (i.e. use existing profile as inspiration) but make sure to not deviate from standards. She suggests that if both agree on these common principles, then we can see who can contribute the first draft. The others can then help improve and contribute to this first draft. Mark comments that he sees these 2 parties also on the same line and agrees.

**Comment by shilpa-padgaonkar** [comment]
DT did not interpret the MoM as DT cannot make a contribution for the first draft.

**Comment by jpengar** [comment]
> I would like to request here change from "Shilpa indicates that she thinks the parts are actually saying the same thing, but from different starting points: define own CAMARA profile, not include default options from other profiles, use existing profile as inspiration. She suggests to start with a PR and discuss on that PR. Mark comments on the same line."
> 
> to
> 
> Shilpa indicates that she thinks that both Telefonica and DT are saying the same things but from different starting points: what she can suggest is to define own Camara profile, reuse what work has been done in the past (i.e. use existing profile as inspiration) but make sure to not deviate from standards. She suggests that if both agree on these common principles, then we can see who can contribute the first draft. The others can then help improve and contribute to this first draft. Mark comments that he sees these 2 parties also on the same line and agrees.

@shilpa-padgaonkar Changed in https://github.com/camaraproject/IdentityAndConsentManagement/pull/110/commits/a630fb5db5ab38b2796aadd0883df5fbe009fd46

**Review by shilpa-padgaonkar — APPROVED** [review]
/LGTM

**Comment by jpengar** [comment]
@rartych Could you please check so we can merge the notes?

**Review by rartych — APPROVED** [review]
LGTM

**Pull request merged**
