### PR TITLE
Update README and CHANGELOG for release v0.1.0

### LINKED ISSUE #88: Creating the first release for id and consent subproject
**Problem description**
Given that we had an initial short term agreement on the use of purpose for the consent solution, we should create an initial release tag 0.1. This will help kickstart topics beyond the short term agreement and other long term improvements.

**Expected action**
Decision on which currently open PRs need to be part of this first release
Release tag 0.1 is created

**Additional context**

### PR DESCRIPTION
**Pull request by jpengar**
#### What type of PR is this?

* subproject management

#### What this PR does / why we need it:

PR to update CHANGELOG.md & README.md with baseline release v0.1.0 info

#### Which issue(s) this PR fixes:

Partially fixes #88. This PR is the last step before creating the v0.1.0 release branch and tag, and eventually creating the v0.1.0 release of the github repository.

#### Special notes for reviewers:

Just make sure you agree with the CHANGELOG content added considering that this is the first release and it still does not use the defined changelog section template (Added, Changed, Fixed, etc...).

#### Changelog input

N/A

#### Additional documentation 

N/A

### CODE REVIEW

**Comment by jpengar** [comment]
@Elisabeth-Ericsson FYI

**Review by bigludo7 — APPROVED** [review]
LGTM

**Comment by jpengar** [comment]
@rartych et all, could you please take a look at this PR? It shouldn't take too long and we need to merge this to finally create the v0.1.0 release. Thanks a lot in advance.

P.D: Thanks Robert for your prompt review. You deserve a place in heaven! :P

**Review by shilpa-padgaonkar — APPROVED** [review]
/LGTM

**Review by rartych — APPROVED** [review]
I have edited subproject name to look nicer :)
LGTM now.

**Comment by jpengar** [comment]
Thanks to both @rartych & @shilpa-padgaonkar 

I will give it some more time today in case we get more reviews, but if not, I will merge this PR by the end of the day.

**Pull request merged**
