### PR TITLE
IdentityAndConsentManagement meeting notes 2023-10-18

### PR DESCRIPTION
**Pull request by jpengar**
#### What type of PR is this?
* documentation

#### What this PR does / why we need it:

MoM of the call held in 2023-10-18

#### Which issue(s) this PR fixes:

None.

### CODE REVIEW

**Comment by jpengar** [comment]
Guys, do you have any comments on the meeting notes? If not, could you give your approval to merge the PR?

(CC @rartych)

**Comment by jpengar** [comment]
@rartych kind reminder :P

**Review by rartych — APPROVED** [review]
LGTM

Should we change the date of the next call in this MoM?

**Comment by jpengar** [comment]
> LGTM
> 
> 
> 
> Should we change the date of the next call in this MoM?

Let's merge it as is for simplicity. At that point in time was not known what was going to happen with Nov 1st meeting. The meeting has been cancelled already and properly communicated to everyone.

**Pull request merged**
