### PR TITLE
Fix W3C DPV broken links in ICM doc

### LINKED ISSUE #195: W3C Data Privacy Vocabulary (DPV) reference links in ICM documentation are broken
**Problem description**
W3C Data Privacy Vocabulary (DPV) reference links in ICM documentation are broken. It appears that with the DPV 2.0 release, previous reference links are no longer valid. Affected documents:
* CAMARA-API-access-and-user-consent.md
* CAMARA-Security-Interoperability.md

Reference links should be updated to:
* https://w3c.github.io/dpv/
* https://w3c.github.io/dpv/2.0/dpv/
* https://w3c.github.io/dpv/2.0/dpv/#vocab-purposes 

**Expected behavior**
Correct/update reference links in ICM documentation.

**Alternative solution**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by jpengar**
#### What type of PR is this?

* correction
* documentation

#### What this PR does / why we need it:

W3C Data Privacy Vocabulary (DPV) reference links in ICM documentation are broken. This PR fixes the broken links in the required documents.

#### Which issue(s) this PR fixes:

Fixes #195

#### Special notes for reviewers:

N/A

#### Changelog input

```
Fix W3C Data Privacy Vocabulary (DPV) broken reference links

```

#### Additional documentation 

N/A

### CODE REVIEW

**Review by AxelNennker — APPROVED** [review]

**Comment by hdamker** [comment]
My view would be to start to work on a Maintenance Release r0.2.1 which includes this and maybe other fixes which will come up. If the APIs are not impacted directly (in sense: they need to adapt something) and the corrections have some value for the audience, I would be in favour of such release with a patch version.

And it is foreseen with Release Management - within the API_Release_Guidelines there is the following description:
> Maintenance release
> 
> In case a patch update of a public API version x.y.z is required, the patched public API version x.y.z+1 shall be created through a maintenance release on a separate branch referred to as a maintenance branch.
> 
> NOTE: a patch is the only case for which a separate branch is created and maintained within the API repository (as pull requests should be prepared within forks of the API repository, c.f. [Governance/CONTRIBUTING.md](https://github.com/camaraproject/Governance/blob/main/CONTRIBUTING.md))

The reasoning ist that the `main` branch should not be blocked by the Maintenance Release(s) of the Fall24 version. But as long you haven't done anything within the main branch you can do the updates also there and create the Maintenance Release (or doing it vice versa: merging the Maintenance branch also into `main` afterwards).

**Comment by hdamker** [comment]
BTW: You may want to clean up the 16 branches which are left from previous PRs - normally that can be done already safely when the PR is merged.

**Comment by jpengar** [comment]
@hdamker @camaraproject/release-management_maintainers Would it then be okay to merge this PR into `main` (we haven't made any changes to `main` since the r0.2.0 public release), and then create the maintenance release branch from `main`?

Should I call this maintenance branch `r0.2.1`? `r0.2.1-maintenance`? Is there any naming convention for this? 

Then we can wait a reasonable amount of time, in case other fixes are needed, before creating the tag and the actual maintenance release `r0.2.1` on github.

**Comment by jpengar** [comment]
We can wait for feedback from Release Management, I see no problem with that. For me, it looks good to merge this PR into `main`, and then create a new branch `maintenance-r0.2` from `main`.

**Comment by jpengar** [comment]
@hdamker @camaraproject/release-management_maintainers Did you manage to review this topic about the maintenance releases?

**Comment by hdamker** [comment]
> @hdamker @camaraproject/release-management_maintainers Did you manage to review this topic about the maintenance releases?

I wasn't in the last Release Management meeting, but guess that don't. I have created https://github.com/camaraproject/ReleaseManagement/issues/93 for that.

**Comment by hdamker** [comment]
> @hdamker @camaraproject/release-management_maintainers Did you manage to review this topic about the maintenance releases?

@jpengar as a short-term solution: as long as there is no other PR for a later version merged into `main` you can just create the patch release on `main` itself.

**Comment by tanjadegroot** [comment]
For maintenance releases of APIs, the process is described here: https://lf-camaraproject.atlassian.net/wiki/spaces/CAM/pages/14559630/API+Release+Process#PATCH-update.

We could add something similar to the comm/ICM process part (with the exception that it would use the version number iso the release nr for Fall24 patches.)

**Pull request merged**
