### PR TITLE
IdentityAndConsentManagement meeting notes 2023-10-04

### PR DESCRIPTION
**Pull request by jpengar**
#### What type of PR is this?
* documentation

#### What this PR does / why we need it:

MoM of the call held in 2023-10-04

#### Which issue(s) this PR fixes:

None.

### CODE REVIEW

**Review by bigludo7 — APPROVED** [review]
LGTM Thanks
I've send by email to Jesùs the point related to PR #33 "Consent-related use cases".

**Comment by jpengar** [comment]
Any other comments?
(CC @rartych)

**Comment by jpengar** [comment]
Since there are no other comments from last week. @rartych , if possible, could you provide your review and approval as code owner to be able to merge the meeting minutes. Thanks in advance!

**Review by rartych — APPROVED** [review]
LGTM

**Pull request merged**
