### PR TITLE
Consent-related use cases 

### PR DESCRIPTION
**Pull request by bigludo7**
Draft version - List of Use Case illustrating (or not) requirement for consent.

#### What type of PR is this?

Add one of the following kinds:

* documentation

#### What this PR does / why we need it:

The objective of the PR is to contribute to a document listing consent related use-cases. Thi document will be use as an output for Consent API work.

#### Which issue(s) this PR fixes:

No issue

#### Special notes for reviewers:

This is a **DRAFT** document. 

#### Changelog input

```
 release-note

```

#### Additional documentation 

This section can be blank.

```
docs

```

### CODE REVIEW

**Comment by rartych** [comment]
Fixes #21

**Comment by shilpa-padgaonkar** [comment]
@bigludo7 : Thanks for the PR. 
Good to see different usecases elaborated for individuals vs enterprise, data subjects versus no-data subject and onetime vs time-limited consent.

We have thought of certain scenarios (though I have not explicitly written them in user story format). 

Just listing them down below for you to take a look. (with No expectation that any part makes its way into the doc in some form :) )

**Scenario1:** Target device, user device, authentication device are the same.
Can be safely assumed that we can request consent from the subscriber/end user

**Scenario2:** Target device and user device are the same but authentication device is different. For e.g. Family sim card

**Scenario3:** User device and authentication device are same but target device is different. For e.g. Parent using tracking app for child’s device

**Scenario4:** Target device, user device  and authentication device are all different. 

Two main aspects need to be considered in scenario 2, 3 and 4:
·       Target device could be used by a minor, adult (family sim cards), employee (enterprise mobile devices -- this seems to be already covered in one of your user stories) or does not target a data subject at all (covered in IoT case user story but only for enterprise not individual).
·       Authentication device could have a sim from the same or from a different MNO.

**Comment by rartych** [comment]
Since in the consent document we have the definition of :
_`Aggregator`: aggregate Operator’s CAMARA standardised APIs for building services offered to application developers. An aggregator can be a **hyperscaler** offering its own services or directly exposing CAMARA APIs available at the operators, or it can be a telco operator acting as an aggregator_

I propose to replace _hyperscaler_ with _aggregator_ in this document.
@bigludo7 is it OK for you if I prepare change suggestions that you can commit in the bulk?

**Comment by bigludo7** [comment]
@rartych Sure ! please move forward. I need also to take into account Shilpa comments.

**Comment by rartych** [comment]
Another interesting use case is considered in [Blockchain Public Address](https://github.com/camaraproject/BlockchainPublicAddress/issues/16) subproject.

Currently it considers giving consent to data access not to applications/service providers but to specific subscribers identified by MSISDN using this applications - kind of whitelisting who can get information about given subscriber from Telco operator.

The problem may be also solved on API level (not using consent management system) or even on the specific application level.

This problem can be also interesting for identity related use-cases.

**Comment by gmuratk** [comment]
I recall a document with a few use cases listed, but I can't seem to locate it at this time.  
In the meeting notes from Sept 6, 2023, it is stated that discussion and progress will continue offline. Is it possible to gain visibility into progress?  
Also Is this progress expected to produce a new section in the [https://github.com/camaraproject/IdentityAndConsentManagement/blob/main/documentation/CAMARA-API-access-and-user-consent.md#introduction](url)?  
Thank you,

**Comment by bigludo7** [comment]
@gmuratk Yes my bad - I've accidentally remove this file. I will reinsert it.

**Comment by jpengar** [comment]
This PR has been restored in https://github.com/camaraproject/IdentityAndConsentManagement/pull/74

**Pull request closed without merging**
